function distWeibull(X1, Y1, X2, Y2)
%CREATEFIGURE(X1,Y1,X2,Y2)
%  X1:  vector of x data
%  Y1:  vector of y data
%  X2:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 05-Dec-2013 01:00:07

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'Tag','main',...
    'XTick',[0 5000 10000 15000 20000 25000 30000 35000 40000],...
    'OuterPosition',[-0.00178571428571429 -0.00238095238095238 1 1],...
    'FontSize',18,...
    'ColorOrder',[1 0 0;0 0 1;0.666666666666667 0.333333333333333 0;0.333333333333333 0.333333333333333 0.333333333333333;1 0 1;1 1 0;1 0.666666666666667 0.333333333333333;0.666666666666667 0.666666666666667 0.666666666666667;0.666666666666667 0.333333333333333 1;0 0.666666666666667 0.333333333333333;0.666666666666667 0 0.333333333333333;1 0.333333333333333 0.666666666666667;0 1 0;0.333333333333333 0.666666666666667 1;0.666666666666667 1 0.333333333333333;0.333333333333333 0 0.666666666666667;0 0.333333333333333 0.666666666666667;0.333333333333333 1 0.666666666666667;0 0 0;0.333333333333333 0.666666666666667 0;0.333333333333333 0 0.666666666666667],...
    'CLim',[0 1],...
    'ALim',[0 1]);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 43631.5]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 0.000819973221236269]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create xlabel
xlabel('Time Lapse (mins)','FontSize',18);

% Create ylabel
ylabel('Game play','FontSize',18););

% Create plot
plot(X1,Y1,'Parent',axes1,'Tag','dfdata','LineWidth',1,...
    'Color',[0.333333333333333 0 0.666666666666667],...
    'DisplayName','Time data');

% Create plot
plot(X2,Y2,'Parent',axes1,'Tag','distfit','LineWidth',2,'LineStyle','--',...
    'Color',[1 0 0],...
    'DisplayName','Weibull Distribution');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Interpreter','none','EdgeColor',[1 1 1],'YColor',[1 1 1],...
    'XColor',[1 1 1]);

