
%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/connylin/Documents/Lab/Lab Archive/Lab Archive
%    Projects/Lab Project Embryonic Exposure/EE Dose Titration 55
%    Physical/Data/DataRaw Summary/ET55 F1-F3 Raw Data.xlsx Worksheet: exp
%    code
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2014/03/28 16:04:39

%% Import the data
[~, ~, raw] = xlsread('/Users/connylin/Documents/Lab/Lab Archive/Lab Archive Projects/Lab Project Embryonic Exposure/EE Dose Titration 55 Physical/Data/DataRaw Summary/ET55 F1-F3 Raw Data.xlsx','exp code');
raw = raw(2:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[2,8,11,14]);
raw = raw(:,[1,3,4,5,6,7,9,10,12,13]);

%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
ET55F1F3RawData = table;

%% Allocate imported array to column variable names
ET55F1F3RawData.ID = data(:,1);
ET55F1F3RawData.groupname = cellVectors(:,1);
ET55F1F3RawData.duration = data(:,2);
ET55F1F3RawData.timing = data(:,3);
ET55F1F3RawData.conc = data(:,4);
ET55F1F3RawData.VarName6 = data(:,5);
ET55F1F3RawData.conc_code = data(:,6);
ET55F1F3RawData.conL = cellVectors(:,2);
ET55F1F3RawData.VarName9 = data(:,7);
ET55F1F3RawData.duration_code = data(:,8);
ET55F1F3RawData.durationL = cellVectors(:,3);
ET55F1F3RawData.VarName12 = data(:,9);
ET55F1F3RawData.timing_code = data(:,10);
ET55F1F3RawData.timing_L = cellVectors(:,4);

%% Clear temporary variables
clearvars data raw cellVectors R;