function createfigure(D,gname,sampletime,C)
%CREATEFIGURE(XMATRIX1,YMATRIX1,EMATRIX1)
%  XMATRIX1:  errorbar x matrix
%  YMATRIX1:  errorbar y matrix
%  EMATRIX1:  errorbar e matrix

%  Auto-generated by MATLAB on 02-Jan-2014 01:21:46
gray = [0.8 0.8 0.8];
blue = [0 0 1];
black = [0 0 0];
green = [0 0.498039215803146 0];
pink = [0.749019622802734 0 0.749019622802734];
purple = [0.47843137383461 0.062745101749897 0.894117653369904];
lightblue = [0 0.749019622802734 0.749019622802734];
orange = [0.87058824300766 0.490196079015732 0];
yellow = [1 1 0];
white = [1 1 1];
red = [1 0 0];
color = [black;red;gray;pink];

% subplot position
plotposition(1,:) = [0.09 0.75 0.40 0.20];
plotposition(2,:) = [0.56 0.75 0.40 0.20];
plotposition(3,:) = [0.09 0.45 0.40 0.20];
plotposition(4,:) = [0.56 0.45 0.40 0.20];
plotposition(5,:) = [0.09 0.15 0.40 0.20];
plotposition(6,:) = [0.56 0.15 0.40 0.20];

measure = {'aspect';'kink';'width';'curve';'length'};

% Create figure
figure1 = figure('Color',[1 1 1]);





for m = 1:numel(measure)
    
axes1 = axes('Parent',figure1,'XLim',[0 max(sampletime)+10],...
    'Position',plotposition(m,:));
%% set ylim
Y = D.(measure{m}).Y;
E = D.(measure{m}).E;
XC = C.(measure{m}).t;
YC = C.(measure{m}).Y;
EC = (C.(measure{m}).E).*sqrt(C.(measure{m}).N);

ymin = min(min([Y,YC]-[E,EC])); ymin = ymin-(ymin*.1);
ymax = max(max([Y,YC]+[E,EC])); ymax = ymax+(ymax*.1);
%%
ylim(axes1,[ymin ymax]);
%%
xlim(axes1,[0 420]); 
hold(axes1,'all');

% plot control
area(XC,YC+EC,'FaceColor',[0.8 0.8 0.8],'EdgeColor','w');
hold on;
area(XC,YC-EC,'FaceColor',[1 1 1],'EdgeColor','w');



X = D.(measure{m}).t;
Y = D.(measure{m}).Y;
E = D.(measure{m}).E;
errorbar1 = errorbar(X,Y,E,'Marker','.');
if size(X,2) <= size(color,1)
    for g = 1:size(X,2)
       set(errorbar1(g),'DisplayName',gname{g},...
            'LineWidth',0.5,'Color',color(g,1:3),...
            'MarkerSize',6,'Marker','.'); 
    end
end



ylabel((measure{m})); % Create ylabel

end

% SAVE FIGURE
savefigpdf('Posture_ByGroup',pSaveA);
display 'Posture_ByGroup graphing done';
