function [MWTftrv] = importtrvNsave(pExpStd,pExpStdSave)
display ' ';
[~,expname] = fileparts(pExpStd);
display('Importing trv generated by Choreography...');
str = 'from [%s]';
display(sprintf(str,expname));
[MWTftrv] = revtrvreversalcompile(pExpStd);
% validate import
% saving
[savename] = creatematsavename(pExpStd,'import_','.mat'); % create save name
cd(pExpStdSave);
save(savename);
display('done');