function makefigwithinexp(GraphData,g,setfilename,titlename,pFun,Yn,pBet)
%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 24-Jul-2013 13:26:23
cd(pFun);
Graph = load(setfilename);
% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1,...
    'Position',[0.13 0.11 0.575985915492958 0.815]);
box(axes1,'on');
hold(axes1,'all');
box(axes1,'on');
hold(axes1,'all');


% Create multiple lines using matrix input to plot
plot1 = plot(GraphData{g,3},'Parent',axes1);
for p = 1:size(GraphData{g,3},2);
    set(plot1(p),'DisplayName',GraphData{g,2}{p,1});
end



xlabel('Time'); % Create xlabel
ylabel(Yn); % Create ylabel

legend1 = legend(axes1,'show');
set(legend1,'EdgeColor',[1 1 1],'YColor',[1 1 1],'XColor',[1 1 1],...
    'Position',[0.739450493346209 0.0843580597586709 0.246537142476609 0.847631864674578]);
% Create textbox
annotation(figure1,'textbox',...
    [0.0397323943661972 0.954659949622166 0.322943661971831 0.0403022670025186],...
    'String',GraphData(g,1),...
    'FontSize',12,...
    'FontWeight','bold',...
    'FontName','Arial',...
    'FitBoxToText','off',...
    'EdgeColor','none');

savefig(titlename,pBet);
close
end

