function sd3 = stdcombine(n1,m1,sd1,n2,m2,sd2)
%% calculate std of two combined data
% reference http://stats.stackexchange.com/questions/55999/is-it-possible-to-find-the-combined-standard-deviation

sd3 = sqrt(...
                (...
                    n1*sd1^2 + ...
                    n2*sd2^2 + ...
                    n1*(m1-m2)^2 + ...
                    n2*(m2-m1)^2)...
                /(n1+n1)...
        );
end